name: hello-world

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello world!"

      - name: Say goodbye
        run: echo "Goodbye world!"
